config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :posts
  resources :students
  root "students#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :reviews
  validates :lesson, presence: true
  validates :name, presence: true
  validates :date, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  def set_search
    @search = Student.order(created_at: :desc).ransack(params[:q])
    @students = @search.result(distinct: true)
  end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new # フォーム用の空のインスタンスを生成する。
  end

  def create
    @post = Post.new(post_params) # ストロングパラメータを引数に
    @post.save # saveをしてデータベースに保存する。
    redirect_to @post # showページにリダイレクト
  end

  def show
    @post = Post.find(params[:id])
  end


  private

  def post_params # ストロングパラメータを定義する
    params.require(:post).permit(:title, :body, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review.student, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:student_id, :body)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy,]
  
  def index
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      flash.now[:alert] = @student.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @student.update(student_params)
    redirect_to students_path
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:lesson, :name, :date, :note)
  end

  def set_student
    @student = Student.find(params[:id])
  end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TkuP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <div class="container">
        
        <%= link_to "TKUC", students_path, class:"navbar-brand" %>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="ナビゲーションの切替">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            
              <%= link_to "登録", new_student_path, class: "nav-link"  %>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
          <div class="col-md-12">
            <div class="form-inline float-right mb-3">
              <%= search_form_for @search do |f| %>
                <div class="form-group">
                  <%= f.search_field :name_or_lesson_cont, placeholder: "タイトルか本文を検索", class: "form-control" %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>ブログ記事投稿</h1>
    <%= form_with model: @post, local: true do |form| %>
      <div class="form-group">
        <%= form.label "タイトル" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label "カテゴリ" %>
        <%= form.text_field :category, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label "本文" %>
        <%= form.text_area :body, class: "form-control" %>
      </div>
      <%= form.submit '登録する', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @post.title %></h1>
    <p>カテゴリ: <%= @post.category %></p>
    <p>投稿日:<%= @post.created_at %></p>
    <hr>
    <%= simple_format(@post.body) %>
    <hr>
    <%= link_to "編集", edit_post_path(@post), class: "btn btn-secondary" %>
    <%= link_to "削除", post_path(@post), class: "btn btn-danger", method: :delete %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.student_id %></td>
        <td><%= review.body %></td>
        <td><%= link_to 'Show', review %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @review.student_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/students/_new_review.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :student_id, id: :review_student_id %>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>授業編集フォーム</h1>
<% if flash["alert"].present? %>
  <% flash["alert"].each do |value| %>
    <%= content_tag(:div, value) %>
  <% end %>
<% end %>
<%= form_with model: @student, local: true do |form| %>
  <p>
    授業名<br>
    <%= form.text_field :lesson %>
  </p>

  <p>
    教授名<br>
    <%= form.text_field :name %>
  </p>

  <p>
    時間<br>
    <%= form.text_field :date %>
  </p>

  <p>
    備考<br>
    <%= form.text_field :note %>
  </p>

  <%= form.submit "更新" %>
<% end %>

app/views/students/index.html.erb
<h1>TKUCとは</h1>
<p>講義について評価する場です。</p>


<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.lesson, student_path(student)%></li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>新規授業登録フォーム</h1>
<% if flash["alert"].present? %>
  <% flash["alert"].each do |value| %>
    <%= content_tag(:div, value) %>
  <% end %>
    
<% end %>
<%= form_with model: @student, local: true do |form| %>
  <p>
    授業名<br>
    <%= form.text_field :lesson %>
  </p>

  <p>
    教授名<br>
    <%= form.text_field :name %>
  </p>

  <p>
    時間<br>
    <%= form.text_field :date %>
  </p>

  <p>
    備考<br>
    <%= form.text_field :note %>
  </p>

  <%= form.submit "登録" %>
<% end %>
  

app/views/students/show.html.erb
<div class="row">
  <div class="col-md-8">
    <p>
      <b>講義名：<%= @student.lesson %></b>
    </p>

    <p>
      <b>教授名：<%= @student.name %></b>
    </p>

    <p>
      <b>時間：<%= @student.date %></b>
    </p>

    <p>
      <b>備考：<%= @student.note %></b>
    </p>

    <p>
      <%= link_to "編集", edit_student_path(@student) %>
    </p>
  </div>
</div>

<table class="table table-bordered table-striped">
  <div class="col-md-8">
      <% @student.reviews.each do |review| %>
        <li><%= review.body %>- <%= review.created_at %></li>
      <% end %>
  
    
  </div>
</table>



<div class="form-inline float-right mb-8">
  <h3>投稿</h3>
  <%= render partial: 'new_review', locals:{review: @student.reviews.new} %>
</div>